on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: choice
        required: true
        options:
          - staging
          - prod
      description:
        description: "Description to add"
        type: string

jobs:
  log-the-inputs:
    name: Workflow Dispatch Testing
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "---- Based on Env ----"
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "---- Based on inputs directly ----"
          echo "Log level: ${{ inputs.logLevel}}"
          echo "Tags: ${{ inputs.tags }}"
          echo "Environment: ${{ inputs.environment }}"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
